//Rextester.Program.Main is the entry point for your code. Don't change it.
//Compiler version 4.0.30319.17929 for Microsoft (R) .NET Framework 4.5
/*ProjectEuler.net Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


using System;

namespace Rextester
{
    public class Program
    {
        public static void Main(string[] args)
        {
            int F1=1;
            int F2=2;
            int Fn=0;
            
            while(F2 < 4000000)
            {
                //need to filter odd Fibs.
                if(1 == (F2%2))
                    continue;
                else
                    Fn += F2;
                F2 = F2+F1;
                F1 = F2-F1;
            }
            Console.WriteLine("{0}", Fn);
        }
    }
}
