/*Gordon Stangler
Project Euler Problem 9
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.
There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
*/

/*
All Pythagorean triples are generated by a= (m*m - n*n), b = 2mn, c = (m*m + n*n), where m>n.
To generated them uniquely, gcd(m,n)=1 and m-n is odd.  I am assuming that the solution may
not be a primitive triplet.
*/

int main()
{
  int a,b,c,m,n;
  m=1;
  n=0;

  for(m;m<1000;m++)
  {
    for(n;n<m;n++)
    {
      a = (m*m - n*n);
      b = 2*m*n;
      c = (m*m + n*n);

      if((a+b+c) == 1000)
      {
        printf("The product of a = %d, b = %d, and c = %d is %d.\n", a,b,c,(a*b*c));
        break;
      }
    }
    n=0;
  }

return 0;
}