/*ProjectEuler.net Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <stdio.h>

int main()
{
	int F1, F2, Fn;	/*F1,F2 are the previous and current Fib. number, while Fn is the sum of the evens.*/

	F1 = 1;
	F2 = 2;
	Fn = 0;

	while (F2 < 4000000)
	{
		if((F2)&(0x1)) //F2 is odd
			Fn += 0;
		else
			Fn += F2;

		/*Adds the two, then makes F1 the old F2.  We do this at the end to force the while(true) check.*/
		F2 = F1 + F2;
		F1 = F2-F1;
	}

	printf("%i", Fn);
	return 0;
}